baseURL = "https://codeiscanon.com/"
languageCode = "en-us"
title = "Code Is Canon"
theme = ["ananke"]
googleAnalytics = "G-BRREP3YRS1"
enableRobotsTXT = true

[sitemap]
changefreq = "weekly"
filename = "sitemap.xml"
priority = 0.5

[params]
favicon = "insignificantbit.svg"  
description = "Programming blog of my learnings and experiences in Java, AWS and Kafka"
read_more_copy = "Continue reading on codeiscanon"
featured_image = "images/insignificantbit-featured.webp"
images = ["images/insignificantbit-featured.webp"]
title = "Code Is Canon"
commentoEnable = true

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
