baseURL = "https://insignificantbit.com/"
languageCode = "en-us"
title = "Insignificant Bit"
theme = "ananke"
googleAnalytics = "G-BV6ZJ9DQ96"
[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5