baseURL = "https://insignificantbit.com/"
languageCode = "en-us"
title = "Insignificant Bit"
theme = "ananke"
googleAnalytics = "UA-184602811-1"
enableRobotsTXT = true

[sitemap]
changefreq = "weekly"
filename = "sitemap.xml"
priority = 0.5

[params]
favicon = "insignificantbit.svg"  
description = "Programming blog of learnings and experiences in Java, AWS and Kafka"
read_more_copy = "Continue reading on insignificantbit.com"
featured_image = "images/insignificantbit-featured.webp"
images = ["images/insignificantbit-featured.webp"]
title = "Insignificant Bit"

[taxonomies]
series = "series"