baseURL = "https://insignificantbit.com/"
languageCode = "en-us"
title = "Insignificant Bit"
theme = "ananke"
googleAnalytics = "UA-184602811-1"
[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5